### ISSUE TITLE
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like CompVis/stable-diffusion-safety-checker is not the path to a directory containing a preprocessor_config.json file.

### ISSUE THREAD

**Issue by wangzhen-ing** [MichalGeyer/plug-and-play#20]
python run_features_extraction.py --config configs/pnp/feature-extraction-real.yaml
Traceback (most recent call last):
  File "/data1/wz/anaconda3/envs/pnp-diffusion/lib/python3.8/site-packages/transformers/feature_extraction_utils.py", line 403, in get_feature_extractor_dict
    resolved_feature_extractor_file = cached_path(
  File "/data1/wz/anaconda3/envs/pnp-diffusion/lib/python3.8/site-packages/transformers/utils/hub.py", line 282, in cached_path
    output_path = get_from_cache(
  File "/data1/wz/anaconda3/envs/pnp-diffusion/lib/python3.8/site-packages/transformers/utils/hub.py", line 545, in get_from_cache
    raise ValueError(
ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_features_extraction.py", line 14, in <module>
    from pnp_utils import check_safety
  File "/data1/wz/research/plug-and-play-main/pnp_utils.py", line 14, in <module>
    safety_feature_extractor = AutoFeatureExtractor.from_pretrained(safety_model_id)
  File "/data1/wz/anaconda3/envs/pnp-diffusion/lib/python3.8/site-packages/transformers/models/auto/feature_extraction_auto.py", line 270, in from_pretrained
    config_dict, _ = FeatureExtractionMixin.get_feature_extractor_dict(pretrained_model_name_or_path, **kwargs)
  File "/data1/wz/anaconda3/envs/pnp-diffusion/lib/python3.8/site-packages/transformers/feature_extraction_utils.py", line 436, in get_feature_extractor_dict
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like CompVis/stable-diffusion-safety-checker is not the path to a directory containing a preprocessor_config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**I would like to ask how you can solve this problem. I downloaded the sd-v1-4.ckpt file directly from the official website of the CompVis organization at Hugging Face, and then put this file directly into models/ldm/stable-diffusion-v1/
Don't know if this is possible?**

**Comment by CostaliyA** [comment]
download the model and change the path

**Comment by wangzhen-ing** [comment]
> download the model and change the path

what means? I have downloaded sd-v1-4.ckpt in models/ldm/stable-diffusion-v1/, but it still fails to work.
Did you successfully run the program? Do you need to make some changes to the package version of the repository?

**Comment by CostaliyA** [comment]
直接把你下载的重命名ckpt文件为model.ckpt放到指定目录

**Comment by CostaliyA** [comment]
然后还得从huggingface上下个clip

**Comment by wangzhen-ing** [comment]
> 然后还得从huggingface上下个clip

这个文件也放到models/ldm/stable-diffusion-v1/这个文件夹下吗

**Comment by CostaliyA** [comment]
无所谓 反正会报错 你把报错里的文件里的load pretrained的路径改成你下clip的路径就行了 你先把model那个下好会有新的报错的

**Comment by CostaliyA** [comment]
The problem arises because some areas cannot access the huggingface properly.

**Comment by quleileileilei** [comment]
have you solved this problem?
